version: '3'
services:
  front:
    build: .
    container_name: vue-app
    ports:
      - "8080:8080"
    networks:
      - back-front-network
networks:
  back-front-network:
    name : back-front-networke

    