version: '3'
services:
  front:
    build: .
    container_name: vue-app
    ports:
      - "8080:8080"
    networks:
      - back-front-network
    restart: always
    volumes:
      - /app/node_modules
networks:
  back-front-network:
    name : back-front-network


    